* HangfireHs Notes

 This repo is for notes about the [[https://github.com/bigos/HangfireHs][HangfireHs]] project.

** Why do I use org mode?

I use [[https://en.wikipedia.org/wiki/Org-mode][Org-mode]] because it is easier for me. Still, you can edit those file
using a regular text editor, so small contributions should not be a problem.
Also you can export org file to md using pandoc.

 #+BEGIN_EXAMPLE
 pandoc -s readme.org -o readme.md
 #+END_EXAMPLE


** Original documentation links

[[https://www.hangfire.io/][Main page]]

[[https://www.hangfire.io/overview.html][Overview]]

[[http://docs.hangfire.io/en/latest/][Detailed documentation]]

** Different goals

Because we potentially target other platform and environments, this place will
be for discussion about different databases support and other back-end storage
issues.

Also, for now, we want to create a simplified product inspired by Hangfire.
Reviewing the strengths of technology we use and the weaknesses of our team, we
will decide about the project scope.

TODO

** Project planning

*** Simple specification of the early prototype.

TODO

**** toy engine for background jobs

Why don't we create some simple code that simulates talking to the database,
possibly making the tests easier as well.

To get us off the ground we could only fire some terminal actions. What you think?

TODO

**** background job types

Don't go yet for all the jobs possible.

***** Fire-and-forget

TODO

***** Delayed

TODO

***** Recurring


 Recurring

 TODO

**** testing

***** easy

 Testing some parts of the system should be fairly trivial.
 [[https:github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/Cron.cs][Cron.cs]]
 should easily translate to Haskell.
 And the same goes for its tests in [[https://github.com/HangfireIO/Hangfire/blob/master/tests/Hangfire.Core.Tests/CronFacts.cs][CronFacts.cs]].


***** hard

There are parts that involve lots of exceptions. An I have no clue how to test
these. Following two links are the relevant source and tests.

[[https:github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.Core/Server/DelayedJobScheduler.cs][DelayedJobScheduler.cs]]

[[https:github.com/HangfireIO/Hangfire/blob/master/tests/Hangfire.Core.Tests/Server/DelayedJobSchedulerFacts.cs][DelayedJobSchedulerFacts.cs]]

*** more TODO later
